import { App, TFile } from "obsidian";
import type { AgentProfile, CardDelivery, CardFrontmatter, CockpitBoardSettings, SessionMode } from "../types";
import { loginEnv, nodeApis, runProcess, startDetached, which, type NodeApis, type RunResult } from "../node";
import { cardIdOf } from "./card-id";
import { absolutePath, boardLink, buildContext, cardTitle } from "./context";
import type { ResolvedMachine } from "./machines";
import { psCall, psq, renderTemplate, shDir, shJoin, shq, slug, splitArgs } from "./shell";

// The agent launcher. Rules every path below follows:
// - Card text (the prompt) is only ever written to a file, sent on stdin, or
//   passed as one argv element to a program started without a shell. It is
//   never part of a script, a shell string or a terminal command line.
// - Scripts and shell strings are built from settings values and our own
//   slugs only, each quoted with shq/psq.

/** Remote folder for uploaded cards and prompts (POSIX, `~` expands). */
const REMOTE_CACHE = "~/.cache/cockpit-board";
/** Windows caps a command line near 32 K characters; stay well below. */
const MAX_ARGV_PROMPT = 24000;

export interface LaunchPlan {
  file: TFile;
  agent: AgentProfile;
  /** null = this computer. */
  machine: ResolvedMachine | null;
  session: SessionMode;
  delivery: CardDelivery;
  /** Working directory; "" = default (vault root locally, home remotely). */
  cwd: string;
  /** The final prompt, as shown (and possibly edited) in the dialog. */
  prompt: string;
}

export class LaunchError extends Error {
  constructor(message: string, public runDir?: string) { super(message); }
}

// ── Pure helpers (unit tested) ──

/** Where the agent reads the card on a remote machine, or undefined when inline. */
export function remoteCardFile(delivery: CardDelivery, machine: ResolvedMachine | null, cardId: string): string | undefined {
  if (!machine || delivery === "inline") return undefined;
  if (delivery === "shared") return joinPosix(machine.sharedRemote, "cockpit", `${slug(cardId)}.md`);
  return `${REMOTE_CACHE}/cards/${slug(cardId)}.md`;
}

function joinPosix(...parts: string[]): string {
  return parts.map((p, i) => (i === 0 ? p.replace(/\/+$/, "") : p.replace(/^\/+|\/+$/g, ""))).filter(Boolean).join("/");
}

/**
 * herdr parses a positional argument that starts with "-" as an option (it
 * ignores "--"), so such a prompt would fail. A leading space is harmless.
 */
export function herdrText(text: string): string {
  return text.startsWith("-") ? ` ${text}` : text;
}

/** SSH options start with "-"; a target must not. */
export function checkSshTarget(target: string): string {
  if (!target || target.startsWith("-")) throw new Error(`Invalid SSH target "${target}".`);
  return target;
}

/** The pointer prompt used when the prompt itself cannot travel as text. */
export function pointerPrompt(path: string): string {
  return `Your task is in the file ${path}. Read it and follow it.`;
}

/** argv for the agent: command plus the profile's arguments. */
export function agentArgv(agent: AgentProfile): string[] {
  return [agent.command.trim() || "claude", ...splitArgs(agent.args)];
}

/** A POSIX `cd <dir> && <agent> "$(cat <prompt file>)"` line. */
export function posixAgentLine(argv: string[], promptFile: string, cwd: string): string {
  const promptExpr = promptFile.startsWith("~/") ? `$(cat ${shDir(promptFile)})` : `$(cat ${shq(promptFile)})`;
  const cd = cwd ? `cd ${shDir(cwd)} && ` : "";
  return `${cd}${shJoin(argv)} "${promptExpr}"`;
}

/** Local POSIX launch script: login PATH, cd, run the agent, keep a shell. */
export function posixScript(opts: { pathEnv?: string; body: string }): string {
  return [
    "#!/bin/sh",
    "# Generated by Cockpit Board. Card text is read from files, never inlined here.",
    ...(opts.pathEnv ? [`export PATH=${shq(opts.pathEnv)}`] : []),
    opts.body,
    "exec \"${SHELL:-/bin/sh}\" -l",
    "",
  ].join("\n");
}

/** Local PowerShell launch script. */
export function powershellScript(lines: string[]): string {
  return ["# Generated by Cockpit Board. Card text is read from files, never inlined here.", ...lines, ""].join("\r\n");
}

/** Template variables for a card; `cardFile` is where the agent reads it. */
export async function promptVars(app: App, file: TFile, cardFile?: string): Promise<Record<string, string>> {
  const fm = app.metadataCache.getFileCache(file)?.frontmatter ?? {};
  const labels: unknown = fm.labels;
  const abs = absolutePath(app, file) ?? file.path;
  return {
    context: await buildContext(app, file, cardFile ? { cardFile, includeBody: false } : {}),
    id: cardIdOf(app, file),
    title: cardTitle(app, file),
    path: file.path,
    absPath: abs,
    cardFile: cardFile ?? abs,
    boardLink: boardLink(app, file),
    uri: boardLink(app, file),
    project: typeof fm.project === "string" ? fm.project : "",
    labels: Array.isArray(labels) ? labels.filter((l) => typeof l === "string").join(", ") : "",
  };
}

/** The rendered prompt for a card and agent. */
export async function renderPrompt(app: App, settings: CockpitBoardSettings, file: TFile, agent: AgentProfile, cardFile?: string): Promise<string> {
  const template = agent.promptTemplate.trim() || settings.agentPromptTemplate;
  return renderTemplate(template, await promptVars(app, file, cardFile));
}

/** Terminal command argv with `{script}` replaced; the template is a settings value. */
export function terminalArgv(template: string, script: string): string[] {
  const argv = splitArgs(template);
  if (!argv.some((a) => a.includes("{script}"))) argv.push("{script}");
  return argv.map((a) => a.split("{script}").join(script));
}

/** Terminal presets per OS; the first one found on PATH is the default. */
export const TERMINAL_PRESETS: Record<"linux" | "darwin" | "win32", { name: string; command: string; probe: string }[]> = {
  linux: [
    { name: "xdg-terminal-exec", command: "xdg-terminal-exec {script}", probe: "xdg-terminal-exec" },
    { name: "x-terminal-emulator", command: "x-terminal-emulator -e {script}", probe: "x-terminal-emulator" },
    { name: "Ghostty", command: "ghostty -e {script}", probe: "ghostty" },
    { name: "kitty", command: "kitty {script}", probe: "kitty" },
    { name: "Alacritty", command: "alacritty -e {script}", probe: "alacritty" },
    { name: "WezTerm", command: "wezterm start -- {script}", probe: "wezterm" },
    { name: "GNOME Terminal", command: "gnome-terminal -- {script}", probe: "gnome-terminal" },
    { name: "Konsole", command: "konsole -e {script}", probe: "konsole" },
    { name: "xterm", command: "xterm -e {script}", probe: "xterm" },
  ],
  darwin: [
    { name: "Terminal", command: "open -a Terminal {script}", probe: "open" },
    { name: "iTerm", command: "open -a iTerm {script}", probe: "open" },
    { name: "Ghostty", command: "open -na Ghostty --args -e {script}", probe: "open" },
    { name: "WezTerm", command: "open -na WezTerm --args start -- {script}", probe: "open" },
  ],
  win32: [
    { name: "Windows Terminal", command: "wt.exe -w new powershell.exe -NoExit -NoProfile -ExecutionPolicy Bypass -File {script}", probe: "wt" },
    { name: "PowerShell window", command: "powershell.exe -NoExit -NoProfile -ExecutionPolicy Bypass -File {script}", probe: "powershell" },
  ],
};

export function osKey(platform: string): "linux" | "darwin" | "win32" {
  return platform === "darwin" || platform === "win32" ? platform : "linux";
}

// ── Launch ──

interface Ctx {
  app: App;
  settings: CockpitBoardSettings;
  node: NodeApis;
  env: Record<string, string | undefined>;
  win: boolean;
  mac: boolean;
  runId: string;
  runDir: string;
  cardId: string;
}

/** Start the agent. Resolves with a one-line summary, throws LaunchError. */
export async function launchAgent(app: App, settings: CockpitBoardSettings, plan: LaunchPlan): Promise<string> {
  const node = nodeApis();
  if (!node) throw new LaunchError("Starting agents needs the desktop app.");
  const cardId = cardIdOf(app, plan.file);
  const runId = `${slug(cardId, 30)}-${Date.now().toString(36)}`;
  const runDir = node.path.join(node.os.tmpdir(), "cockpit-board", runId);
  await node.fs.promises.mkdir(runDir, { recursive: true, mode: 0o700 });
  const ctx: Ctx = {
    app, settings, node, runId, runDir, cardId,
    env: await loginEnv(node),
    win: node.process.platform === "win32",
    mac: node.process.platform === "darwin",
  };
  const promptFile = node.path.join(runDir, "prompt.md");
  await node.fs.promises.writeFile(promptFile, plan.prompt, { encoding: "utf8", mode: 0o600 });

  try {
    if (plan.machine && plan.delivery !== "inline") await deliverCard(ctx, plan);
    let where: string;
    if (plan.session === "herdr") where = await launchHerdr(ctx, plan, promptFile);
    else if (plan.session === "tmux") where = await launchTmux(ctx, plan, promptFile);
    else where = await launchTerminal(ctx, plan, promptFile);
    const summary = `${plan.agent.name} · ${plan.machine?.name ?? "this computer"} · ${where}`;
    if (settings.agentRecordRuns) await recordRun(app, plan.file, summary);
    return summary;
  } catch (e: unknown) {
    throw new LaunchError(e instanceof Error ? e.message : String(e), runDir);
  }
}

async function recordRun(app: App, file: TFile, summary: string): Promise<void> {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  const stamp = `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
  await app.fileManager.processFrontMatter(file, (fm: CardFrontmatter) => {
    const runs = Array.isArray(fm.agent_runs) ? (fm.agent_runs as unknown[]).filter((r) => typeof r === "string") : [];
    fm.agent_runs = [...runs, `${stamp} · ${summary}`];
  });
}

function firstLine(r: RunResult): string {
  const text = (r.stderr || r.stdout).trim();
  try {
    const j = JSON.parse(text) as { error?: { message?: string; code?: string } };
    if (j.error?.message) return j.error.code ? `${j.error.code}: ${j.error.message}` : j.error.message;
  } catch { /* not JSON */ }
  return text.split(/\r?\n/)[0] || `exit code ${r.code}`;
}

// ── SSH ──

function sshCmd(ctx: Ctx): string {
  return ctx.settings.agentLocal.sshPath || "ssh";
}

/** Run a command string on the remote (non-interactive). */
async function ssh(ctx: Ctx, m: ResolvedMachine, remoteCmd: string, input?: string, timeoutMs = 30000): Promise<RunResult> {
  const r = await runProcess(ctx.node, sshCmd(ctx), ["-o", "BatchMode=yes", checkSshTarget(m.sshTarget), remoteCmd], { env: ctx.env, input, timeoutMs });
  if (r.code === 255) {
    throw new Error(`SSH to ${m.sshTarget} failed: ${firstLine(r)}. Run "ssh ${m.sshTarget}" once in a terminal (key, host check).`);
  }
  return r;
}

/** Write `content` to a remote path under the cache folder (path from our slugs only). */
async function uploadText(ctx: Ctx, m: ResolvedMachine, relPath: string, content: string): Promise<string> {
  const remote = `${REMOTE_CACHE}/${relPath}`;
  const dir = remote.slice(0, remote.lastIndexOf("/"));
  const r = await ssh(ctx, m, `mkdir -p ${shDir(dir)} && umask 077 && cat > ${shDir(remote)}`, content);
  if (r.code !== 0) throw new Error(`Upload to ${m.name} failed: ${firstLine(r)}`);
  return remote;
}

async function deliverCard(ctx: Ctx, plan: LaunchPlan): Promise<void> {
  const m = plan.machine!;
  const content = await ctx.app.vault.read(plan.file);
  const name = `${slug(ctx.cardId)}.md`;
  if (plan.delivery === "upload") {
    await uploadText(ctx, m, `cards/${name}`, content);
    return;
  }
  // Shared folder: copy here, then wait until the machine sees it.
  const localDir = ctx.node.path.join(expandHome(ctx, m.sharedLocal), "cockpit");
  await ctx.node.fs.promises.mkdir(localDir, { recursive: true });
  await ctx.node.fs.promises.writeFile(ctx.node.path.join(localDir, name), content, "utf8");
  const remote = remoteCardFile("shared", m, ctx.cardId)!;
  const deadline = Date.now() + 60000;
  for (;;) {
    const r = await ssh(ctx, m, `test -f ${shDir(remote)}`);
    if (r.code === 0) return;
    if (Date.now() > deadline) throw new Error(`The card copy is not visible on ${m.name} after 60 s (${remote}). Is the shared folder syncing?`);
    await new Promise((res) => window.setTimeout(res, 3000));
  }
}

function expandHome(ctx: Ctx, p: string): string {
  return p === "~" || p.startsWith("~/") || p.startsWith("~\\") ? ctx.node.os.homedir() + p.slice(1) : p;
}

/** The working directory on this computer: plan, else vault root. */
function localCwd(ctx: Ctx, plan: LaunchPlan): string {
  if (plan.cwd) return expandHome(ctx, plan.cwd);
  const vaultRoot = absolutePath(ctx.app, plan.file);
  return vaultRoot ? vaultRoot.slice(0, vaultRoot.length - plan.file.path.length).replace(/[\\/]+$/, "") : ctx.node.os.homedir();
}

/** The prompt file on the machine that runs the agent (uploads it for remote). */
async function promptOnTarget(ctx: Ctx, plan: LaunchPlan, promptFile: string): Promise<string> {
  if (!plan.machine) return promptFile;
  return uploadText(ctx, plan.machine, `runs/${ctx.runId}.md`, plan.prompt);
}

// ── herdr ──

async function herdr(ctx: Ctx, plan: LaunchPlan, args: string[], timeoutMs = 30000): Promise<Record<string, unknown>> {
  const prefix = plan.machine ? ["--machine", plan.machine.herdrLabel] : [];
  const cmd = ctx.settings.agentLocal.herdrPath || "herdr";
  const r = await runProcess(ctx.node, cmd, [...prefix, ...args], { env: ctx.env, timeoutMs });
  if (r.code !== 0) {
    if (r.code === 127) throw new Error(`herdr not found. Install it or set its path in settings.`);
    throw new Error(`herdr ${args[0]} ${args[1] ?? ""}: ${firstLine(r)}`);
  }
  try { return JSON.parse(r.stdout) as Record<string, unknown>; } catch { return {}; }
}

async function launchHerdr(ctx: Ctx, plan: LaunchPlan, promptFile: string): Promise<string> {
  if (plan.machine && !plan.machine.herdrLabel) throw new Error(`${plan.machine.name} is not a herdr machine (herdr machine list).`);
  const title = cardTitle(ctx.app, plan.file);
  const label = `${ctx.cardId} ${title}`.slice(0, 60);
  const cwd = plan.machine ? plan.cwd : localCwd(ctx, plan);
  const created = await herdr(ctx, plan, ["workspace", "create", ...(cwd ? ["--cwd", cwd] : []), "--label", label, "--focus"]);
  const result = (created.result ?? {}) as { root_pane?: { pane_id?: string }; workspace?: { workspace_id?: string } };
  const pane = result.root_pane?.pane_id;
  const ws = result.workspace?.workspace_id;
  if (!pane || !ws) throw new Error("herdr did not return the new workspace's pane.");

  if (plan.agent.herdrKind) {
    const name = `cb-${slug(ctx.cardId, 24)}-${ctx.runId.slice(-4)}`;
    const extra = splitArgs(plan.agent.args);
    await herdr(ctx, plan, ["agent", "start", name, "--kind", plan.agent.herdrKind, "--pane", pane, "--timeout", "60000",
      ...(extra.length ? ["--", ...extra] : [])], 70000);
    // The prompt travels as one argv element (no shell); a very long one goes
    // through a file instead.
    const text = plan.prompt.length > MAX_ARGV_PROMPT ? pointerPrompt(await promptOnTarget(ctx, plan, promptFile)) : plan.prompt;
    await herdr(ctx, plan, ["agent", "prompt", name, herdrText(text)]);
  } else {
    const target = await promptOnTarget(ctx, plan, promptFile);
    const line = !plan.machine && ctx.win
      ? psCall([...agentArgv(plan.agent), pointerPrompt(target)])
      : posixAgentLine(agentArgv(plan.agent), target, "");
    await herdr(ctx, plan, ["pane", "run", pane, line]);
  }

  // Display-only metadata: sheprd shows "card <id>" with card_link clickable.
  // herdr 0.9.3 wants the workspace id first. Optional, so a failure only
  // goes to the console.
  try {
    await herdr(ctx, plan, ["workspace", "report-metadata", ws, "--source", "cockpit-board",
      "--token", `card=${ctx.cardId}`, "--token", `card_link=${boardLink(ctx.app, plan.file)}`], 5000);
  } catch (e: unknown) {
    console.warn("Cockpit Board: herdr workspace metadata not set", e);
  }
  return `herdr ${ws}`;
}

// ── Terminal ──

/** Write a launch script (from settings + slugs only) and return its path. */
async function writeScript(ctx: Ctx, name: string, content: string): Promise<string> {
  const p = ctx.node.path.join(ctx.runDir, name);
  await ctx.node.fs.promises.writeFile(p, content, { encoding: "utf8", mode: 0o700 });
  return p;
}

async function terminalTemplate(ctx: Ctx): Promise<string> {
  const custom = ctx.settings.agentLocal.terminalCommand.trim();
  if (custom) return custom;
  const presets = TERMINAL_PRESETS[osKey(ctx.node.process.platform)];
  for (const p of presets) if (await which(ctx.node, p.probe)) return p.command;
  return presets[presets.length - 1].command;
}

async function openTerminal(ctx: Ctx, script: string): Promise<void> {
  const argv = terminalArgv(await terminalTemplate(ctx), script);
  try {
    await startDetached(ctx.node, argv[0], argv.slice(1), { env: ctx.env, cwd: ctx.runDir });
  } catch (e: unknown) {
    throw new Error(`Could not open a terminal (${argv[0]}): ${e instanceof Error ? e.message : String(e)}. Set the terminal command in settings.`);
  }
}

/** Script name per OS: macOS Terminal opens `.command` files. */
function scriptName(ctx: Ctx, base: string): string {
  return ctx.win ? `${base}.ps1` : ctx.mac ? `${base}.command` : `${base}.sh`;
}

async function launchTerminal(ctx: Ctx, plan: LaunchPlan, promptFile: string): Promise<string> {
  const argv = agentArgv(plan.agent);
  let script: string;
  if (!plan.machine) {
    const cwd = localCwd(ctx, plan);
    if (ctx.win) {
      // Windows PowerShell 5.1 mangles double quotes in native arguments, so
      // the agent gets a pointer to the prompt file, never the text.
      script = powershellScript([`Set-Location -LiteralPath ${psq(cwd)}`, `${psCall([...argv, pointerPrompt(promptFile)])}`]);
    } else {
      script = posixScript({ pathEnv: ctx.env.PATH, body: posixAgentLine(argv, promptFile, cwd) });
    }
  } else {
    const remotePrompt = await promptOnTarget(ctx, plan, promptFile);
    const remoteLine = ctx.win
      ? `${plan.cwd ? `cd ${shDir(plan.cwd)} && ` : ""}${shJoin([...argv, pointerPrompt(remotePrompt)])}; exec $SHELL -l`
      : `${posixAgentLine(argv, remotePrompt, plan.cwd)}; exec "$SHELL" -l`;
    const sshArgv = [sshCmd(ctx), "-t", checkSshTarget(plan.machine.sshTarget), remoteLine];
    script = ctx.win
      ? powershellScript([psCall(sshArgv)])
      : posixScript({ pathEnv: ctx.env.PATH, body: shJoin(sshArgv) });
  }
  await openTerminal(ctx, await writeScript(ctx, scriptName(ctx, "run"), script));
  return "new terminal";
}

// ── tmux ──

async function launchTmux(ctx: Ctx, plan: LaunchPlan, promptFile: string): Promise<string> {
  const session = ctx.settings.agentLocal.tmuxSession.trim() || "cockpit";
  const windowName = slug(ctx.cardId, 30);
  const argv = agentArgv(plan.agent);

  if (plan.machine) {
    const m = plan.machine;
    const remotePrompt = await promptOnTarget(ctx, plan, promptFile);
    // Always cd: a new window otherwise starts wherever the tmux server did.
    const inner = `${posixAgentLine(argv, remotePrompt, plan.cwd || "~")}; exec "$SHELL" -l`;
    const remote = `tmux has-session -t ${shq(session)} 2>/dev/null || tmux new-session -d -s ${shq(session)}; ` +
      `tmux new-window -t ${shq(`${session}:`)} -n ${shq(windowName)} ${shq(inner)}`;
    const r = await ssh(ctx, m, remote);
    if (r.code !== 0) throw new Error(`tmux on ${m.name}: ${firstLine(r)}`);
    if (ctx.settings.agentLocal.attachTmux) {
      const attach = [sshCmd(ctx), "-t", checkSshTarget(m.sshTarget), `tmux attach -t ${shq(session)}`];
      const script = ctx.win ? powershellScript([psCall(attach)]) : posixScript({ pathEnv: ctx.env.PATH, body: shJoin(attach) });
      await openTerminal(ctx, await writeScript(ctx, scriptName(ctx, "attach"), script));
    }
    return `tmux ${session}:${windowName} on ${m.name}`;
  }

  // Local. On Windows tmux runs inside WSL, with paths translated.
  const tmux = async (args: string[]): Promise<RunResult> => ctx.win
    ? runProcess(ctx.node, "wsl.exe", ["tmux", ...args], { env: ctx.env, timeoutMs: 15000 })
    : runProcess(ctx.node, ctx.settings.agentLocal.tmuxPath || "tmux", args, { env: ctx.env, timeoutMs: 15000 });
  const toWsl = async (p: string): Promise<string> => {
    const r = await runProcess(ctx.node, "wsl.exe", ["wslpath", "-a", p], { timeoutMs: 10000 });
    if (r.code !== 0) throw new Error(`WSL is needed for tmux on Windows: ${firstLine(r)}`);
    return r.stdout.trim();
  };

  const cwd = ctx.win ? await toWsl(localCwd(ctx, plan)) : localCwd(ctx, plan);
  const prompt = ctx.win ? await toWsl(promptFile) : promptFile;
  // In WSL the login shell supplies PATH; elsewhere we export the login PATH.
  const body = posixAgentLine(argv, prompt, cwd);
  const scriptPath = await writeScript(ctx, "run-tmux.sh", posixScript({ pathEnv: ctx.win ? undefined : ctx.env.PATH, body }));
  const scriptArg = ctx.win ? await toWsl(scriptPath) : scriptPath;

  const has = await tmux(["has-session", "-t", session]);
  if (has.code === 127) throw new Error(ctx.win ? "WSL is not installed (wsl.exe not found)." : "tmux not found. Install it or set its path in settings.");
  if (has.code !== 0) {
    const r = await tmux(["new-session", "-d", "-s", session]);
    if (r.code !== 0) throw new Error(`tmux new-session: ${firstLine(r)}`);
  }
  const shellArgs = ctx.win ? ["bash", "-l", scriptArg] : ["sh", scriptArg];
  const r = await tmux(["new-window", "-t", `${session}:`, "-n", windowName, "-c", cwd, ...shellArgs]);
  if (r.code !== 0) throw new Error(`tmux new-window: ${firstLine(r)}`);

  if (ctx.settings.agentLocal.attachTmux) {
    const clients = await tmux(["list-clients", "-t", session]);
    if (!clients.stdout.trim()) {
      const script = ctx.win
        ? powershellScript([psCall(["wsl.exe", "tmux", "attach", "-t", session])])
        : posixScript({ pathEnv: ctx.env.PATH, body: shJoin([ctx.settings.agentLocal.tmuxPath || "tmux", "attach", "-t", session]) });
      await openTerminal(ctx, await writeScript(ctx, scriptName(ctx, "attach"), script));
    }
  }
  return `tmux ${session}:${windowName}`;
}

// ── Availability (for the dialog) ──

export interface Availability {
  herdr: boolean;
  tmux: boolean;
  /** Why tmux is unavailable locally, when it is. */
  tmuxReason?: string;
}

export async function localAvailability(settings: CockpitBoardSettings): Promise<Availability> {
  const node = nodeApis();
  if (!node) return { herdr: false, tmux: false, tmuxReason: "desktop only" };
  const herdr = !!(await which(node, settings.agentLocal.herdrPath || "herdr"));
  if (node.process.platform === "win32") {
    const wsl = await runProcess(node, "wsl.exe", ["tmux", "-V"], { timeoutMs: 8000 });
    return wsl.code === 0 ? { herdr, tmux: true } : { herdr, tmux: false, tmuxReason: "needs tmux in WSL" };
  }
  const tmux = !!(await which(node, settings.agentLocal.tmuxPath || "tmux"));
  return tmux ? { herdr, tmux } : { herdr, tmux: false, tmuxReason: "tmux not found" };
}

/** Delete run folders older than a week. */
export async function cleanOldRuns(): Promise<void> {
  const node = nodeApis();
  if (!node) return;
  const root = node.path.join(node.os.tmpdir(), "cockpit-board");
  let entries: string[] = [];
  try { entries = await node.fs.promises.readdir(root); } catch { return; }
  const cutoff = Date.now() - 7 * 86400000;
  for (const name of entries) {
    const p = node.path.join(root, name);
    try {
      if ((await node.fs.promises.stat(p)).mtimeMs < cutoff) await node.fs.promises.rm(p, { recursive: true, force: true });
    } catch { /* gone already */ }
  }
}
